exp_name: "unet_cylinder"
gpu: 0
seed: 0
results_path: "/work/b314513067/pi-lfm/runs"

# data
dataset_name: "cylinder"
dataset_root: "/work/b314513067/pi-lfm/data"
num_workers: 12
normalizer: "gaussian"

# model
model_name: "unet"
is_resume: False
checkpoint_path: './results/unet/unet_cylinder_numerical_False/2025-08-27_00-44-01/model_6400.pth' # for resume training
dim_mults: [1, 2, 4]
mask_prob: 0.5
noise_scale: 0.1 # only applicable for numerical data

# training
is_use_tb: True
epochs: 200
step_size: 50
gamma: 0.5
train_batch_size: 12
test_batch_size: 12
lr: 0.0001
clip_grad_norm: 0.
scheduler: cosine # step, cosine
num_update: 10000

# evaluation
N_plot: 1
N_autoregressive: 1
probe_diagnostic: True
N_plot_probe: 12